USE [master]
GO

/****** Object:  Database [db_kertas_oltp]    Script Date: 8/26/2016 5:14:08 AM ******/
CREATE DATABASE [db_kertas_oltp]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'db_kertas_oltp', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\db_kertas_oltp.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'db_kertas_oltp_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\db_kertas_oltp_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [db_kertas_oltp] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [db_kertas_oltp].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [db_kertas_oltp] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [db_kertas_oltp] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [db_kertas_oltp] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [db_kertas_oltp] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [db_kertas_oltp] SET ARITHABORT OFF 
GO

ALTER DATABASE [db_kertas_oltp] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [db_kertas_oltp] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [db_kertas_oltp] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [db_kertas_oltp] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [db_kertas_oltp] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [db_kertas_oltp] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [db_kertas_oltp] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [db_kertas_oltp] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [db_kertas_oltp] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [db_kertas_oltp] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [db_kertas_oltp] SET  DISABLE_BROKER 
GO

ALTER DATABASE [db_kertas_oltp] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [db_kertas_oltp] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [db_kertas_oltp] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [db_kertas_oltp] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [db_kertas_oltp] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [db_kertas_oltp] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [db_kertas_oltp] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [db_kertas_oltp] SET RECOVERY FULL 
GO

ALTER DATABASE [db_kertas_oltp] SET  MULTI_USER 
GO

ALTER DATABASE [db_kertas_oltp] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [db_kertas_oltp] SET DB_CHAINING OFF 
GO

ALTER DATABASE [db_kertas_oltp] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [db_kertas_oltp] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [db_kertas_oltp] SET  READ_WRITE 
GO


