DELETE FROM [dbo].[fact_npk]
DELETE FROM [dbo].[fact_penjualan]
DELETE FROM [dbo].[fact_retur]
DELETE FROM [dbo].[dim_npk]
DELETE FROM [dbo].[dim_penjualan]
DELETE FROM [dbo].[dim_kertas]
DELETE FROM [dbo].[dim_konsumen]
DELETE FROM [dbo].[dim_waktu]