USE [master]
GO

/****** Object:  Database [db_kertas_dm]    Script Date: 8/26/2016 5:18:01 AM ******/
CREATE DATABASE [db_kertas_dm]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'db_kertas_dm', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\db_kertas_dm.mdf' , SIZE = 6144KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'db_kertas_dm_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\db_kertas_dm_log.ldf' , SIZE = 1792KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [db_kertas_dm] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [db_kertas_dm].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [db_kertas_dm] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [db_kertas_dm] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [db_kertas_dm] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [db_kertas_dm] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [db_kertas_dm] SET ARITHABORT OFF 
GO

ALTER DATABASE [db_kertas_dm] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [db_kertas_dm] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [db_kertas_dm] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [db_kertas_dm] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [db_kertas_dm] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [db_kertas_dm] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [db_kertas_dm] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [db_kertas_dm] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [db_kertas_dm] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [db_kertas_dm] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [db_kertas_dm] SET  DISABLE_BROKER 
GO

ALTER DATABASE [db_kertas_dm] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [db_kertas_dm] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [db_kertas_dm] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [db_kertas_dm] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [db_kertas_dm] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [db_kertas_dm] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [db_kertas_dm] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [db_kertas_dm] SET RECOVERY FULL 
GO

ALTER DATABASE [db_kertas_dm] SET  MULTI_USER 
GO

ALTER DATABASE [db_kertas_dm] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [db_kertas_dm] SET DB_CHAINING OFF 
GO

ALTER DATABASE [db_kertas_dm] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [db_kertas_dm] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [db_kertas_dm] SET  READ_WRITE 
GO


